title: "Ngome Biz"
theme: minima
description: Privacy Policy and Terms
markdown: kramdown
url: "https://ngomebiz.github.io"
baseurl: ""

permalink: pretty

header_pages:
  - index.md
  - privacy-policy.md
  - terms.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
